### User Register
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
  "firstName": "Anurag",
  "lastName": "Sharma",
  "email": "anurag.user@example.com",
  "password": "User@12345",
  "profileImageUrl": "https://example.com/avatars/user.png"
}

### User Login
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
  "email": "anurag.user@example.com",
  "password": "User@12345"
}

### Author Register
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
  "firstName": "Vikas",
  "lastName": "Author",
  "email": "vikas.author@example.com",
  "password": "Author@12345",
  "profileImageUrl": "https://example.com/avatars/author.png"
}


### Author Register
POST http://localhost:4000/author-api/users
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "Author",
  "email": "test.author@example.com",
  "password": "testauthor",
  "profileImageUrl": "https://example.com/avatars/author.png"
}

### Author Login
POST http://localhost:4000/common-api/login
Content-Type: application/json

{
  "email": "vikas.author@example.com",
  "password": "Author@12345"
}



### Create article (AUTHOR)
POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
  "author":"698ab9bc3fb2728cb77a00dd",
  "title":"test2 article",
  "category":"programming",
  "content":"content of test2 article"
}



###Read articles of a author
GET http://localhost:4000/author-api/articles/698ab9bc3fb2728cb77a00dd


### Update article (AUTHOR)
PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{
  "author":"698ab9bc3fb2728cb77a00dd",
  "articleId":"698ac3d4111dc0e5032907f4",
  "title":"test2 article updated",
  "category":"programming",
  "content":"content of test2 article updated"
}



### Logout
POST http://localhost:4000/common-api/logout